# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFileUpload',
            fields=[
                ('pk_id', models.AutoField(db_column='pk_id', primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
