# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_code_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofileupload',
            name='new_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
